### ISSUE TITLE
PyPI is missing version 3.7.2

### ISSUE THREAD

**Issue by mtelka** [jaraco/jaraco.path#5]
There is the [v3.7.2](https://github.com/jaraco/jaraco.path/releases/tag/v3.7.2) git tag, but such version is [missing at PyPI](https://pypi.org/project/jaraco.path/#history).

**Comment by jaraco** [comment]
Indeed. I can see the [deployment failed](https://github.com/jaraco/jaraco.path/actions/runs/10610173018) due to a failed docs check.

**Comment by jaraco** [comment]
The log is gone there, but when I check out that revision, the docs build fails with this error:

```
../NEWS (links).rst:9: ERROR: Unknown interpreted text role "user". [docutils]
```

It seems the support for linking usernames (2beb8b0c9d0f7046370e7c58c4e6baaf35154a16) was added only after the changelog was rendered (ec200227226108abdd943d2264360619b9d35ddc). I've just cut the release manually as the problem is resolved at HEAD.
